config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end

  def new 
 	  @item = Item.new
  end

  def show
 	@item = Item.find(params[:id])
  end

  def create
  	if Item.create(item_params)
  		redirect_to items_path
  	else
  		render :new
  	end
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  		redirect_to items_path
  	else
  		render :edit
  	end
  end

  def destroy
  	Item.find(params[:id]).destroy
  	redirect_to items_path
  end

 private

	def item_params
		params.require(:item).permit(:name, :description, :complete)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @item do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<%= f.label :complete %>
	<%= f.check_box :complete %>
	<%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1> TODO LIST: </h1>
<p> <%= link_to 'New Post', new_item_path %> </p>
<% @items.each do |item| %>
	<h2> <%= item.name %> </h2>
	<p> <%= item.description %> </p>
	<p> <%= item.complete %> </p>
	<%= link_to 'Show Item', item_path(item) %>
	<%= link_to 'Edit', edit_item_path(item) %>
	<%= link_to 'Delete', item_path(item), method: :delete %>
<% end %>

app/views/items/new.html.erb
<h1> Add a new Todo list </h1>
<%= form_for @item do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<%= f.label :complete %>
	<%= f.check_box :complete %>
<%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1> TODO </h1>
<h2> <%= @item.name %> </h2>
<p> <%= @item.description %> </p>
<p> <%= @item.complete %> </p>
<%= link_to 'Back', items_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Items', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>